version: '3'
services:

  redis:
    container_name: plab_toprate_redis
    image: redis:6-buster
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: --appendonly yes

  app:
    container_name: plab_toprate_api
    image: plab_toprate_backend/app
    restart: always
    volumes:
      - ./:/app/
    command: bash -c "uvicorn app.main:get_app --reload --host 0.0.0.0 --port 5001"
    environment:
      - PYTHONUNBUFFERED
      - DEBUG
    ports:
      - "5001:5001"
    env_file:
      - ./.env.dev.

volumes:
  redisdata:

networks:
  default:
