version: '3'
services:

  db:
    container_name: plab_toprate_db
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5443:5432"
    env_file:
      - ./.env

volumes:
  pgdata:
